# Generated by Django 5.2.7 on 2026-01-09 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="material",
            name="quantity",
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name="material",
            name="received_quantity",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
