# Generated by Django 5.2.7 on 2026-01-18 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="paid",
        ),
    ]
