# Generated by Django 5.2.7 on 2026-03-02 19:44

from django.db import migrations, models


def backfill_order_numbers(apps, schema_editor):
    Order = apps.get_model("orders", "Order")
    # First clear all to avoid unique constraint issues
    Order.objects.all().update(no=None)
    # Then assign sequential numbers by creation date
    for i, order in enumerate(Order.objects.order_by("created_at"), start=1):
        Order.objects.filter(pk=order.pk).update(no=i)


def reverse_backfill(apps, schema_editor):
    Order = apps.get_model("orders", "Order")
    Order.objects.all().update(no=None)


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_remove_order_paid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="number",
        ),
        migrations.AddField(
            model_name="order",
            name="no",
            field=models.PositiveIntegerField(editable=False, null=True, unique=True),
        ),
        migrations.RunPython(
            backfill_order_numbers,
            reverse_backfill,
        ),
    ]
