# Generated by Django 5.2.7 on 2026-01-23 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("labours", "0001_initial"),
        ("rate_work", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ratepayment",
            name="labour",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rate_work_payments",
                to="labours.labour",
            ),
        ),
    ]
