# Generated by Django 5.2.7 on 2026-01-23 14:14

from django.db import migrations


def copy_labour(apps, schema_editor):
    RatePayment = apps.get_model("rate_work", "RatePayment")

    for rp in RatePayment.objects.select_related("rate_work__labour").iterator():
        if rp.rate_work and rp.rate_work.labour:
            rp.labour_id = rp.rate_work.labour_id
            rp.save(update_fields=["labour"])


class Migration(migrations.Migration):

    dependencies = [
        ("rate_work", "0002_ratepayment_labour"),
    ]

    operations = [
        migrations.RunPython(copy_labour),
    ]
