# Generated by Django 5.2.7 on 2026-01-23 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("labours", "0001_initial"),
        ("rate_work", "0003_copy_labour_to_ratepayment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ratework",
            name="site",
        ),
        migrations.RemoveField(
            model_name="ratepayment",
            name="rate_work",
        ),
        migrations.AlterField(
            model_name="ratepayment",
            name="labour",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rate_work_payments",
                to="labours.labour",
            ),
        ),
        migrations.AddField(
            model_name="ratework",
            name="date_created",
            field=models.DateField(auto_now=True),
        ),
    ]
