# Generated by Django 5.2.7 on 2026-01-14 06:17

import django.db.models.deletion
import django_resized.forms
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("sites", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Labour",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                (
                    "previous_balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("pan_number", models.CharField(blank=True, max_length=12)),
                ("aadhar_number", models.CharField(blank=True, max_length=12)),
                ("bank_account_number", models.CharField(blank=True, max_length=24)),
                ("ifsc_code", models.CharField(blank=True, max_length=30)),
                ("branch_name", models.CharField(blank=True, max_length=30)),
                (
                    "type",
                    models.IntegerField(choices=[(1, "Daily Work"), (2, "Rate Work")]),
                ),
                ("gender", models.IntegerField(choices=[(1, "Male"), (2, "Female")])),
                (
                    "photo",
                    django_resized.forms.ResizedImageField(
                        blank=True,
                        crop=None,
                        force_format="webp",
                        keep_meta=True,
                        quality=80,
                        scale=None,
                        size=[1920, 1080],
                        upload_to="labours/pfp/",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="labours",
                        to="sites.site",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LabourDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("file_name", models.CharField(blank=True, max_length=100)),
                (
                    "document",
                    models.FileField(blank=True, upload_to="labours/documents/"),
                ),
                (
                    "labour",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="labours.labour",
                    ),
                ),
            ],
        ),
    ]
