# Generated by Django 5.2.7 on 2026-01-18 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vendors", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="vendor",
            name="ifsc_code",
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
