# Generated by Django 5.2.7 on 2026-01-21 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vendors", "0002_vendor_ifsc_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="vendor",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
