# Generated by Django 5.2.7 on 2026-03-02 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vendors", "0003_vendor_is_deleted"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="vendor",
            options={},
        ),
    ]
