# Generated by Django 5.2.7 on 2026-01-21 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sites", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="site",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
