# Generated by Django 5.2.7 on 2026-01-13 12:51

import django.db.models.deletion
import django_resized.forms
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("sites", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("date_created", models.DateField(auto_now_add=True)),
                ("note", models.CharField(blank=True, default="", max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Labour",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                (
                    "previous_balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("aadhar_number", models.CharField(blank=True, max_length=12)),
                ("bank_account_number", models.CharField(blank=True, max_length=24)),
                ("ifsc_code", models.CharField(blank=True, max_length=30)),
                ("branch_name", models.CharField(blank=True, max_length=30)),
                (
                    "type",
                    models.IntegerField(choices=[(1, "Daily Work"), (2, "Rate Work")]),
                ),
                ("gender", models.IntegerField(choices=[(1, "Male"), (2, "Female")])),
                (
                    "photo",
                    django_resized.forms.ResizedImageField(
                        blank=True,
                        crop=None,
                        force_format="webp",
                        keep_meta=True,
                        quality=80,
                        scale=None,
                        size=[1920, 1080],
                        upload_to="labours/pfp/",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="labours",
                        to="sites.site",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LabourDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("file_name", models.CharField(blank=True, max_length=100)),
                (
                    "document",
                    models.FileField(blank=True, upload_to="labours/documents/"),
                ),
                (
                    "labour",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="payroll.labour",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RateWork",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "quantity",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("unit", models.CharField(max_length=30)),
                (
                    "cost_per_unit",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("is_completed", models.BooleanField(default=False)),
                (
                    "labour",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rate_works",
                        to="payroll.labour",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rate_works",
                        to="sites.site",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Week",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("start_date", models.DateField(help_text="Must be a Saturday")),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="week",
                        to="sites.site",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DailyEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField()),
                ("admin_unlocked", models.BooleanField(default=False)),
                ("is_saved", models.BooleanField(default=False)),
                (
                    "week",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="days",
                        to="payroll.week",
                    ),
                ),
            ],
            options={
                "ordering": ["date"],
                "unique_together": {("week", "date")},
            },
        ),
        migrations.CreateModel(
            name="WeekLabourAssignment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "weekly_daily_wage",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="The fixed daily wage for this labourer during this specific week.",
                        max_digits=10,
                    ),
                ),
                (
                    "labour",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="payroll.labour",
                    ),
                ),
                (
                    "week",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="payroll.week"
                    ),
                ),
            ],
            options={
                "unique_together": {("week", "labour")},
            },
        ),
        migrations.AddField(
            model_name="week",
            name="labours",
            field=models.ManyToManyField(
                related_name="weeks",
                through="payroll.WeekLabourAssignment",
                to="payroll.labour",
            ),
        ),
        migrations.CreateModel(
            name="LabourAttendance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_present", models.BooleanField(default=False)),
                (
                    "wage_for_day",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "advance_taken",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "daily_entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendances",
                        to="payroll.dailyentry",
                    ),
                ),
                (
                    "labour",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_records",
                        to="payroll.labour",
                    ),
                ),
            ],
            options={
                "unique_together": {("daily_entry", "labour")},
            },
        ),
        migrations.CreateModel(
            name="RatePayment",
            fields=[
                (
                    "payment_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="payroll.payment",
                    ),
                ),
                (
                    "rate_work",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="payroll.ratework",
                    ),
                ),
            ],
            bases=("payroll.payment",),
        ),
        migrations.AlterUniqueTogether(
            name="week",
            unique_together={("site", "start_date")},
        ),
    ]
