# Generated by Django 5.2.7 on 2026-01-14 06:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("labours", "0001_initial"),
        ("sites", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Week",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("start_date", models.DateField(help_text="Must be a Saturday")),
                ("admin_unlocked", models.BooleanField(default=False)),
                ("is_saved", models.BooleanField(default=False)),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="week",
                        to="sites.site",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DailyEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField()),
                ("admin_unlocked", models.BooleanField(default=False)),
                ("is_saved", models.BooleanField(default=False)),
                (
                    "week",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="days",
                        to="payroll.week",
                    ),
                ),
            ],
            options={
                "ordering": ["date"],
                "unique_together": {("week", "date")},
            },
        ),
        migrations.CreateModel(
            name="WeekLabourAssignment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "weekly_daily_wage",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="The fixed daily wage for this labourer during this specific week.",
                        max_digits=10,
                    ),
                ),
                (
                    "labour",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="labours.labour",
                    ),
                ),
                (
                    "week",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="payroll.week"
                    ),
                ),
            ],
            options={
                "unique_together": {("week", "labour")},
            },
        ),
        migrations.AddField(
            model_name="week",
            name="labours",
            field=models.ManyToManyField(
                related_name="weeks",
                through="payroll.WeekLabourAssignment",
                to="labours.labour",
            ),
        ),
        migrations.CreateModel(
            name="LabourPayment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "amount_paid",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "labour",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="week_payment",
                        to="payroll.weeklabourassignment",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LabourAttendance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_present", models.BooleanField(default=False)),
                (
                    "advance_taken",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "daily_entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendances",
                        to="payroll.dailyentry",
                    ),
                ),
                (
                    "labour",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_records",
                        to="labours.labour",
                    ),
                ),
            ],
            options={
                "unique_together": {("daily_entry", "labour")},
            },
        ),
        migrations.AlterUniqueTogether(
            name="week",
            unique_together={("site", "start_date")},
        ),
    ]
