# Generated by Django 5.2.7 on 2026-01-14 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="week",
            name="is_saved",
        ),
        migrations.AlterField(
            model_name="dailyentry",
            name="admin_unlocked",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name="week",
            name="admin_unlocked",
            field=models.BooleanField(default=True),
        ),
    ]
