# Generated by Django 5.2.7 on 2026-01-18 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "payroll",
            "0002_remove_week_is_saved_alter_dailyentry_admin_unlocked_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="labourattendance",
            name="payment_type",
            field=models.IntegerField(
                blank=True, choices=[(1, "Cash"), (2, "Bank Transfer")], default=1
            ),
        ),
    ]
