# Generated by Django 5.2.7 on 2026-01-18 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0003_labourattendance_payment_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="labourpayment",
            name="payment_type",
            field=models.IntegerField(
                blank=True, choices=[(1, "Bank Transfer"), (2, "Cash")], default=1
            ),
        ),
        migrations.AlterField(
            model_name="labourattendance",
            name="payment_type",
            field=models.IntegerField(
                blank=True, choices=[(1, "Bank Transfer"), (2, "Cash")], default=1
            ),
        ),
    ]
