# Generated by Django 5.2.7 on 2026-01-27 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0004_labourpayment_payment_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='labourattendance',
            name='multiplier',
            field=models.FloatField(blank=True, default=1),
        ),
    ]
