# Generated by Django 5.2.7 on 2026-03-06 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("daybook", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="entry",
            name="payment_type",
            field=models.IntegerField(
                blank=True, choices=[(1, "Bank Transfer"), (2, "Cash")], default=1
            ),
        ),
        migrations.AddField(
            model_name="entry",
            name="reference",
            field=models.CharField(default="", max_length=200),
        ),
    ]
